environment:
  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python35
    - PYTHON: C:\Python36
    - PYTHON: C:\Python37

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

# Not a .NET project, we build in the install step instead
build: false

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  - python -m pip install --upgrade pip virtualenv
  - virtualenv --python=python venv
  - venv\Scripts\activate
  - python --version

  # Install the dependencies of the project.
  - pip install --upgrade pip setuptools>=27.0 wheel
  - pip install -e .[tests]
  - pip install coverage

test_script:
  - coverage run --source duecredit -m py.test -v
  - python setup.py install

# for interactive debugging upon completion (have 30 min to react)
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
